# DEVELOPMENT ONLY - Network troubleshooting version
# This version uses host networking to bypass Docker network isolation

services:
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: raresift
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    network_mode: host  # Use host networking to bypass Docker network isolation
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - uploads_data:/app/uploads
      - ./video_assets:/app/video_assets
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/raresift
      - REDIS_URL=redis://localhost:6379
      - SECRET_KEY=dev-secret-key-change-in-production
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: npm run dev

volumes:
  postgres_data:
  redis_data:
  uploads_data: