services:
  # Backend Service (FastAPI)
  - type: web
    name: RareSift-backend
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  # Frontend Service (Next.js)
  - type: web
    name: RareSift-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://raresift-backend.onrender.com

databases:
  - name: raresift-postgres
    databaseName: raresift
    user: postgres
    region: oregon
    plan: free
    
  - name: raresift-redis
    type: redis
    region: oregon
    plan: free