services:
  # Backend API Service
  - type: web
    name: raresift-backend
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: OPENAI_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: DATABASE_URL
        fromDatabase:
          name: raresift-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: raresift-redis
          property: connectionString
    healthCheckPath: /health
    
  # Redis Cache
  - type: redis
    name: raresift-redis
    region: oregon
    plan: free
    maxmemoryPolicy: allkeys-lru
    
databases:
  # PostgreSQL Database
  - name: raresift-db
    databaseName: raresift
    user: postgres
    region: oregon
    plan: free
    postgresMajorVersion: 15