// Auto-generated frame imports for RareSift local search
// Sample of 180 frames from comprehensive extraction
// Generated by create_frame_sample.py

import driving_camera_gh010001_frame_001 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_001.jpg'
import driving_camera_gh010001_frame_026 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_026.jpg'
import driving_camera_gh010001_frame_051 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_051.jpg'
import driving_camera_gh010001_frame_077 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_077.jpg'
import driving_camera_gh010001_frame_102 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_102.jpg'
import driving_camera_gh010001_frame_128 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_128.jpg'
import driving_camera_gh010001_frame_153 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_153.jpg'
import driving_camera_gh010001_frame_178 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_178.jpg'
import driving_camera_gh010001_frame_204 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_204.jpg'
import driving_camera_gh010001_frame_229 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_229.jpg'
import driving_camera_gh010001_frame_255 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_255.jpg'
import driving_camera_gh010001_frame_280 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_280.jpg'
import driving_camera_gh010001_frame_305 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_305.jpg'
import driving_camera_gh010001_frame_331 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_331.jpg'
import driving_camera_gh010001_frame_356 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_356.jpg'
import driving_camera_gh010001_frame_382 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_382.jpg'
import driving_camera_gh010001_frame_407 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_407.jpg'
import driving_camera_gh010001_frame_432 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_432.jpg'
import driving_camera_gh010001_frame_458 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_458.jpg'
import driving_camera_gh010001_frame_483 from '@/assets/demo-frames-sample/driving_camera_gh010001_frame_483.jpg'
import driving_camera_gh010002_frame_001 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_001.jpg'
import driving_camera_gh010002_frame_008 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_008.jpg'
import driving_camera_gh010002_frame_015 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_015.jpg'
import driving_camera_gh010002_frame_023 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_023.jpg'
import driving_camera_gh010002_frame_030 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_030.jpg'
import driving_camera_gh010002_frame_037 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_037.jpg'
import driving_camera_gh010002_frame_045 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_045.jpg'
import driving_camera_gh010002_frame_052 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_052.jpg'
import driving_camera_gh010002_frame_059 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_059.jpg'
import driving_camera_gh010002_frame_067 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_067.jpg'
import driving_camera_gh010002_frame_074 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_074.jpg'
import driving_camera_gh010002_frame_081 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_081.jpg'
import driving_camera_gh010002_frame_089 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_089.jpg'
import driving_camera_gh010002_frame_096 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_096.jpg'
import driving_camera_gh010002_frame_103 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_103.jpg'
import driving_camera_gh010002_frame_111 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_111.jpg'
import driving_camera_gh010002_frame_118 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_118.jpg'
import driving_camera_gh010002_frame_125 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_125.jpg'
import driving_camera_gh010002_frame_133 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_133.jpg'
import driving_camera_gh010002_frame_140 from '@/assets/demo-frames-sample/driving_camera_gh010002_frame_140.jpg'
import driving_camera_gh010003_frame_001 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_001.jpg'
import driving_camera_gh010003_frame_022 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_022.jpg'
import driving_camera_gh010003_frame_043 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_043.jpg'
import driving_camera_gh010003_frame_064 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_064.jpg'
import driving_camera_gh010003_frame_086 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_086.jpg'
import driving_camera_gh010003_frame_107 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_107.jpg'
import driving_camera_gh010003_frame_128 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_128.jpg'
import driving_camera_gh010003_frame_149 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_149.jpg'
import driving_camera_gh010003_frame_171 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_171.jpg'
import driving_camera_gh010003_frame_192 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_192.jpg'
import driving_camera_gh010003_frame_213 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_213.jpg'
import driving_camera_gh010003_frame_234 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_234.jpg'
import driving_camera_gh010003_frame_256 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_256.jpg'
import driving_camera_gh010003_frame_277 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_277.jpg'
import driving_camera_gh010003_frame_298 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_298.jpg'
import driving_camera_gh010003_frame_319 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_319.jpg'
import driving_camera_gh010003_frame_341 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_341.jpg'
import driving_camera_gh010003_frame_362 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_362.jpg'
import driving_camera_gh010003_frame_383 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_383.jpg'
import driving_camera_gh010003_frame_404 from '@/assets/demo-frames-sample/driving_camera_gh010003_frame_404.jpg'
import driving_camera_gh010004_frame_001 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_001.jpg'
import driving_camera_gh010004_frame_019 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_019.jpg'
import driving_camera_gh010004_frame_037 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_037.jpg'
import driving_camera_gh010004_frame_055 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_055.jpg'
import driving_camera_gh010004_frame_073 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_073.jpg'
import driving_camera_gh010004_frame_091 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_091.jpg'
import driving_camera_gh010004_frame_109 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_109.jpg'
import driving_camera_gh010004_frame_127 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_127.jpg'
import driving_camera_gh010004_frame_145 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_145.jpg'
import driving_camera_gh010004_frame_163 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_163.jpg'
import driving_camera_gh010004_frame_182 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_182.jpg'
import driving_camera_gh010004_frame_200 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_200.jpg'
import driving_camera_gh010004_frame_218 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_218.jpg'
import driving_camera_gh010004_frame_236 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_236.jpg'
import driving_camera_gh010004_frame_254 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_254.jpg'
import driving_camera_gh010004_frame_272 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_272.jpg'
import driving_camera_gh010004_frame_290 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_290.jpg'
import driving_camera_gh010004_frame_308 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_308.jpg'
import driving_camera_gh010004_frame_326 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_326.jpg'
import driving_camera_gh010004_frame_344 from '@/assets/demo-frames-sample/driving_camera_gh010004_frame_344.jpg'
import driving_camera_gh010005_frame_001 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_001.jpg'
import driving_camera_gh010005_frame_017 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_017.jpg'
import driving_camera_gh010005_frame_034 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_034.jpg'
import driving_camera_gh010005_frame_051 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_051.jpg'
import driving_camera_gh010005_frame_068 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_068.jpg'
import driving_camera_gh010005_frame_084 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_084.jpg'
import driving_camera_gh010005_frame_101 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_101.jpg'
import driving_camera_gh010005_frame_118 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_118.jpg'
import driving_camera_gh010005_frame_135 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_135.jpg'
import driving_camera_gh010005_frame_151 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_151.jpg'
import driving_camera_gh010005_frame_168 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_168.jpg'
import driving_camera_gh010005_frame_185 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_185.jpg'
import driving_camera_gh010005_frame_202 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_202.jpg'
import driving_camera_gh010005_frame_218 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_218.jpg'
import driving_camera_gh010005_frame_235 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_235.jpg'
import driving_camera_gh010005_frame_252 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_252.jpg'
import driving_camera_gh010005_frame_269 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_269.jpg'
import driving_camera_gh010005_frame_285 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_285.jpg'
import driving_camera_gh010005_frame_302 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_302.jpg'
import driving_camera_gh010005_frame_319 from '@/assets/demo-frames-sample/driving_camera_gh010005_frame_319.jpg'
import driving_camera_gh010006_frame_001 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_001.jpg'
import driving_camera_gh010006_frame_025 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_025.jpg'
import driving_camera_gh010006_frame_050 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_050.jpg'
import driving_camera_gh010006_frame_075 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_075.jpg'
import driving_camera_gh010006_frame_100 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_100.jpg'
import driving_camera_gh010006_frame_124 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_124.jpg'
import driving_camera_gh010006_frame_149 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_149.jpg'
import driving_camera_gh010006_frame_174 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_174.jpg'
import driving_camera_gh010006_frame_199 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_199.jpg'
import driving_camera_gh010006_frame_223 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_223.jpg'
import driving_camera_gh010006_frame_248 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_248.jpg'
import driving_camera_gh010006_frame_273 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_273.jpg'
import driving_camera_gh010006_frame_298 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_298.jpg'
import driving_camera_gh010006_frame_322 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_322.jpg'
import driving_camera_gh010006_frame_347 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_347.jpg'
import driving_camera_gh010006_frame_372 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_372.jpg'
import driving_camera_gh010006_frame_397 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_397.jpg'
import driving_camera_gh010006_frame_421 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_421.jpg'
import driving_camera_gh010006_frame_446 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_446.jpg'
import driving_camera_gh010006_frame_471 from '@/assets/demo-frames-sample/driving_camera_gh010006_frame_471.jpg'
import driving_camera_gh010007_frame_001 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_001.jpg'
import driving_camera_gh010007_frame_020 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_020.jpg'
import driving_camera_gh010007_frame_039 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_039.jpg'
import driving_camera_gh010007_frame_058 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_058.jpg'
import driving_camera_gh010007_frame_077 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_077.jpg'
import driving_camera_gh010007_frame_097 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_097.jpg'
import driving_camera_gh010007_frame_116 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_116.jpg'
import driving_camera_gh010007_frame_135 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_135.jpg'
import driving_camera_gh010007_frame_154 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_154.jpg'
import driving_camera_gh010007_frame_173 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_173.jpg'
import driving_camera_gh010007_frame_193 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_193.jpg'
import driving_camera_gh010007_frame_212 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_212.jpg'
import driving_camera_gh010007_frame_231 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_231.jpg'
import driving_camera_gh010007_frame_250 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_250.jpg'
import driving_camera_gh010007_frame_269 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_269.jpg'
import driving_camera_gh010007_frame_289 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_289.jpg'
import driving_camera_gh010007_frame_308 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_308.jpg'
import driving_camera_gh010007_frame_327 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_327.jpg'
import driving_camera_gh010007_frame_346 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_346.jpg'
import driving_camera_gh010007_frame_365 from '@/assets/demo-frames-sample/driving_camera_gh010007_frame_365.jpg'
import driving_camera_gh010010_frame_001 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_001.jpg'
import driving_camera_gh010010_frame_036 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_036.jpg'
import driving_camera_gh010010_frame_071 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_071.jpg'
import driving_camera_gh010010_frame_107 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_107.jpg'
import driving_camera_gh010010_frame_142 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_142.jpg'
import driving_camera_gh010010_frame_178 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_178.jpg'
import driving_camera_gh010010_frame_213 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_213.jpg'
import driving_camera_gh010010_frame_248 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_248.jpg'
import driving_camera_gh010010_frame_284 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_284.jpg'
import driving_camera_gh010010_frame_319 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_319.jpg'
import driving_camera_gh010010_frame_355 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_355.jpg'
import driving_camera_gh010010_frame_390 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_390.jpg'
import driving_camera_gh010010_frame_425 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_425.jpg'
import driving_camera_gh010010_frame_461 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_461.jpg'
import driving_camera_gh010010_frame_496 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_496.jpg'
import driving_camera_gh010010_frame_532 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_532.jpg'
import driving_camera_gh010010_frame_567 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_567.jpg'
import driving_camera_gh010010_frame_602 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_602.jpg'
import driving_camera_gh010010_frame_638 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_638.jpg'
import driving_camera_gh010010_frame_673 from '@/assets/demo-frames-sample/driving_camera_gh010010_frame_673.jpg'
import driving_camera_gh020010_frame_001 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_001.jpg'
import driving_camera_gh020010_frame_015 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_015.jpg'
import driving_camera_gh020010_frame_029 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_029.jpg'
import driving_camera_gh020010_frame_043 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_043.jpg'
import driving_camera_gh020010_frame_057 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_057.jpg'
import driving_camera_gh020010_frame_072 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_072.jpg'
import driving_camera_gh020010_frame_086 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_086.jpg'
import driving_camera_gh020010_frame_100 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_100.jpg'
import driving_camera_gh020010_frame_114 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_114.jpg'
import driving_camera_gh020010_frame_128 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_128.jpg'
import driving_camera_gh020010_frame_143 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_143.jpg'
import driving_camera_gh020010_frame_157 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_157.jpg'
import driving_camera_gh020010_frame_171 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_171.jpg'
import driving_camera_gh020010_frame_185 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_185.jpg'
import driving_camera_gh020010_frame_199 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_199.jpg'
import driving_camera_gh020010_frame_214 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_214.jpg'
import driving_camera_gh020010_frame_228 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_228.jpg'
import driving_camera_gh020010_frame_242 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_242.jpg'
import driving_camera_gh020010_frame_256 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_256.jpg'
import driving_camera_gh020010_frame_270 from '@/assets/demo-frames-sample/driving_camera_gh020010_frame_270.jpg'

// Frame metadata for search database
export interface FrameData {
  id: string
  frame_image: any
  confidence: number
  video_source: string
  timestamp: number
  metadata: {
    weather: string
    time_of_day: string
    location: string
    category: string
  }
}

// Generate search database from sampled frames
export const SAMPLE_SEARCH_DATABASE: FrameData[] = [
  {
    id: '1',
    frame_image: driving_camera_gh010001_frame_001,
    confidence: 95,
    video_source: 'GH010001.MP4',
    timestamp: 1,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '2',
    frame_image: driving_camera_gh010001_frame_026,
    confidence: 94,
    video_source: 'GH010001.MP4',
    timestamp: 26,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '3',
    frame_image: driving_camera_gh010001_frame_051,
    confidence: 93,
    video_source: 'GH010001.MP4',
    timestamp: 51,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '4',
    frame_image: driving_camera_gh010001_frame_077,
    confidence: 92,
    video_source: 'GH010001.MP4',
    timestamp: 77,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '5',
    frame_image: driving_camera_gh010001_frame_102,
    confidence: 91,
    video_source: 'GH010001.MP4',
    timestamp: 102,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '6',
    frame_image: driving_camera_gh010001_frame_128,
    confidence: 90,
    video_source: 'GH010001.MP4',
    timestamp: 128,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '7',
    frame_image: driving_camera_gh010001_frame_153,
    confidence: 89,
    video_source: 'GH010001.MP4',
    timestamp: 153,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '8',
    frame_image: driving_camera_gh010001_frame_178,
    confidence: 88,
    video_source: 'GH010001.MP4',
    timestamp: 178,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '9',
    frame_image: driving_camera_gh010001_frame_204,
    confidence: 87,
    video_source: 'GH010001.MP4',
    timestamp: 204,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '10',
    frame_image: driving_camera_gh010001_frame_229,
    confidence: 86,
    video_source: 'GH010001.MP4',
    timestamp: 229,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '11',
    frame_image: driving_camera_gh010001_frame_255,
    confidence: 85,
    video_source: 'GH010001.MP4',
    timestamp: 255,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '12',
    frame_image: driving_camera_gh010001_frame_280,
    confidence: 84,
    video_source: 'GH010001.MP4',
    timestamp: 280,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '13',
    frame_image: driving_camera_gh010001_frame_305,
    confidence: 83,
    video_source: 'GH010001.MP4',
    timestamp: 305,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '14',
    frame_image: driving_camera_gh010001_frame_331,
    confidence: 82,
    video_source: 'GH010001.MP4',
    timestamp: 331,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '15',
    frame_image: driving_camera_gh010001_frame_356,
    confidence: 81,
    video_source: 'GH010001.MP4',
    timestamp: 356,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '16',
    frame_image: driving_camera_gh010001_frame_382,
    confidence: 80,
    video_source: 'GH010001.MP4',
    timestamp: 382,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '17',
    frame_image: driving_camera_gh010001_frame_407,
    confidence: 79,
    video_source: 'GH010001.MP4',
    timestamp: 407,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '18',
    frame_image: driving_camera_gh010001_frame_432,
    confidence: 78,
    video_source: 'GH010001.MP4',
    timestamp: 432,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '19',
    frame_image: driving_camera_gh010001_frame_458,
    confidence: 77,
    video_source: 'GH010001.MP4',
    timestamp: 458,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '20',
    frame_image: driving_camera_gh010001_frame_483,
    confidence: 76,
    video_source: 'GH010001.MP4',
    timestamp: 483,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '21',
    frame_image: driving_camera_gh010002_frame_001,
    confidence: 75,
    video_source: 'GH010002.MP4',
    timestamp: 1,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '22',
    frame_image: driving_camera_gh010002_frame_008,
    confidence: 74,
    video_source: 'GH010002.MP4',
    timestamp: 8,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '23',
    frame_image: driving_camera_gh010002_frame_015,
    confidence: 73,
    video_source: 'GH010002.MP4',
    timestamp: 15,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '24',
    frame_image: driving_camera_gh010002_frame_023,
    confidence: 72,
    video_source: 'GH010002.MP4',
    timestamp: 23,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '25',
    frame_image: driving_camera_gh010002_frame_030,
    confidence: 71,
    video_source: 'GH010002.MP4',
    timestamp: 30,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '26',
    frame_image: driving_camera_gh010002_frame_037,
    confidence: 70,
    video_source: 'GH010002.MP4',
    timestamp: 37,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '27',
    frame_image: driving_camera_gh010002_frame_045,
    confidence: 69,
    video_source: 'GH010002.MP4',
    timestamp: 45,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '28',
    frame_image: driving_camera_gh010002_frame_052,
    confidence: 68,
    video_source: 'GH010002.MP4',
    timestamp: 52,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '29',
    frame_image: driving_camera_gh010002_frame_059,
    confidence: 67,
    video_source: 'GH010002.MP4',
    timestamp: 59,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '30',
    frame_image: driving_camera_gh010002_frame_067,
    confidence: 66,
    video_source: 'GH010002.MP4',
    timestamp: 67,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '31',
    frame_image: driving_camera_gh010002_frame_074,
    confidence: 95,
    video_source: 'GH010002.MP4',
    timestamp: 74,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '32',
    frame_image: driving_camera_gh010002_frame_081,
    confidence: 94,
    video_source: 'GH010002.MP4',
    timestamp: 81,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '33',
    frame_image: driving_camera_gh010002_frame_089,
    confidence: 93,
    video_source: 'GH010002.MP4',
    timestamp: 89,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '34',
    frame_image: driving_camera_gh010002_frame_096,
    confidence: 92,
    video_source: 'GH010002.MP4',
    timestamp: 96,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '35',
    frame_image: driving_camera_gh010002_frame_103,
    confidence: 91,
    video_source: 'GH010002.MP4',
    timestamp: 103,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '36',
    frame_image: driving_camera_gh010002_frame_111,
    confidence: 90,
    video_source: 'GH010002.MP4',
    timestamp: 111,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '37',
    frame_image: driving_camera_gh010002_frame_118,
    confidence: 89,
    video_source: 'GH010002.MP4',
    timestamp: 118,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '38',
    frame_image: driving_camera_gh010002_frame_125,
    confidence: 88,
    video_source: 'GH010002.MP4',
    timestamp: 125,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '39',
    frame_image: driving_camera_gh010002_frame_133,
    confidence: 87,
    video_source: 'GH010002.MP4',
    timestamp: 133,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '40',
    frame_image: driving_camera_gh010002_frame_140,
    confidence: 86,
    video_source: 'GH010002.MP4',
    timestamp: 140,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '41',
    frame_image: driving_camera_gh010003_frame_001,
    confidence: 85,
    video_source: 'GH010003.MP4',
    timestamp: 1,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '42',
    frame_image: driving_camera_gh010003_frame_022,
    confidence: 84,
    video_source: 'GH010003.MP4',
    timestamp: 22,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '43',
    frame_image: driving_camera_gh010003_frame_043,
    confidence: 83,
    video_source: 'GH010003.MP4',
    timestamp: 43,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '44',
    frame_image: driving_camera_gh010003_frame_064,
    confidence: 82,
    video_source: 'GH010003.MP4',
    timestamp: 64,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '45',
    frame_image: driving_camera_gh010003_frame_086,
    confidence: 81,
    video_source: 'GH010003.MP4',
    timestamp: 86,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '46',
    frame_image: driving_camera_gh010003_frame_107,
    confidence: 80,
    video_source: 'GH010003.MP4',
    timestamp: 107,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '47',
    frame_image: driving_camera_gh010003_frame_128,
    confidence: 79,
    video_source: 'GH010003.MP4',
    timestamp: 128,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '48',
    frame_image: driving_camera_gh010003_frame_149,
    confidence: 78,
    video_source: 'GH010003.MP4',
    timestamp: 149,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '49',
    frame_image: driving_camera_gh010003_frame_171,
    confidence: 77,
    video_source: 'GH010003.MP4',
    timestamp: 171,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '50',
    frame_image: driving_camera_gh010003_frame_192,
    confidence: 76,
    video_source: 'GH010003.MP4',
    timestamp: 192,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '51',
    frame_image: driving_camera_gh010003_frame_213,
    confidence: 75,
    video_source: 'GH010003.MP4',
    timestamp: 213,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '52',
    frame_image: driving_camera_gh010003_frame_234,
    confidence: 74,
    video_source: 'GH010003.MP4',
    timestamp: 234,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '53',
    frame_image: driving_camera_gh010003_frame_256,
    confidence: 73,
    video_source: 'GH010003.MP4',
    timestamp: 256,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '54',
    frame_image: driving_camera_gh010003_frame_277,
    confidence: 72,
    video_source: 'GH010003.MP4',
    timestamp: 277,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '55',
    frame_image: driving_camera_gh010003_frame_298,
    confidence: 71,
    video_source: 'GH010003.MP4',
    timestamp: 298,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '56',
    frame_image: driving_camera_gh010003_frame_319,
    confidence: 70,
    video_source: 'GH010003.MP4',
    timestamp: 319,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '57',
    frame_image: driving_camera_gh010003_frame_341,
    confidence: 69,
    video_source: 'GH010003.MP4',
    timestamp: 341,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '58',
    frame_image: driving_camera_gh010003_frame_362,
    confidence: 68,
    video_source: 'GH010003.MP4',
    timestamp: 362,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '59',
    frame_image: driving_camera_gh010003_frame_383,
    confidence: 67,
    video_source: 'GH010003.MP4',
    timestamp: 383,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '60',
    frame_image: driving_camera_gh010003_frame_404,
    confidence: 66,
    video_source: 'GH010003.MP4',
    timestamp: 404,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '61',
    frame_image: driving_camera_gh010004_frame_001,
    confidence: 95,
    video_source: 'GH010004.MP4',
    timestamp: 1,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '62',
    frame_image: driving_camera_gh010004_frame_019,
    confidence: 94,
    video_source: 'GH010004.MP4',
    timestamp: 19,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '63',
    frame_image: driving_camera_gh010004_frame_037,
    confidence: 93,
    video_source: 'GH010004.MP4',
    timestamp: 37,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '64',
    frame_image: driving_camera_gh010004_frame_055,
    confidence: 92,
    video_source: 'GH010004.MP4',
    timestamp: 55,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '65',
    frame_image: driving_camera_gh010004_frame_073,
    confidence: 91,
    video_source: 'GH010004.MP4',
    timestamp: 73,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '66',
    frame_image: driving_camera_gh010004_frame_091,
    confidence: 90,
    video_source: 'GH010004.MP4',
    timestamp: 91,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '67',
    frame_image: driving_camera_gh010004_frame_109,
    confidence: 89,
    video_source: 'GH010004.MP4',
    timestamp: 109,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '68',
    frame_image: driving_camera_gh010004_frame_127,
    confidence: 88,
    video_source: 'GH010004.MP4',
    timestamp: 127,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '69',
    frame_image: driving_camera_gh010004_frame_145,
    confidence: 87,
    video_source: 'GH010004.MP4',
    timestamp: 145,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '70',
    frame_image: driving_camera_gh010004_frame_163,
    confidence: 86,
    video_source: 'GH010004.MP4',
    timestamp: 163,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '71',
    frame_image: driving_camera_gh010004_frame_182,
    confidence: 85,
    video_source: 'GH010004.MP4',
    timestamp: 182,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '72',
    frame_image: driving_camera_gh010004_frame_200,
    confidence: 84,
    video_source: 'GH010004.MP4',
    timestamp: 200,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '73',
    frame_image: driving_camera_gh010004_frame_218,
    confidence: 83,
    video_source: 'GH010004.MP4',
    timestamp: 218,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '74',
    frame_image: driving_camera_gh010004_frame_236,
    confidence: 82,
    video_source: 'GH010004.MP4',
    timestamp: 236,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '75',
    frame_image: driving_camera_gh010004_frame_254,
    confidence: 81,
    video_source: 'GH010004.MP4',
    timestamp: 254,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '76',
    frame_image: driving_camera_gh010004_frame_272,
    confidence: 80,
    video_source: 'GH010004.MP4',
    timestamp: 272,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '77',
    frame_image: driving_camera_gh010004_frame_290,
    confidence: 79,
    video_source: 'GH010004.MP4',
    timestamp: 290,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '78',
    frame_image: driving_camera_gh010004_frame_308,
    confidence: 78,
    video_source: 'GH010004.MP4',
    timestamp: 308,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '79',
    frame_image: driving_camera_gh010004_frame_326,
    confidence: 77,
    video_source: 'GH010004.MP4',
    timestamp: 326,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '80',
    frame_image: driving_camera_gh010004_frame_344,
    confidence: 76,
    video_source: 'GH010004.MP4',
    timestamp: 344,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '81',
    frame_image: driving_camera_gh010005_frame_001,
    confidence: 75,
    video_source: 'GH010005.MP4',
    timestamp: 1,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '82',
    frame_image: driving_camera_gh010005_frame_017,
    confidence: 74,
    video_source: 'GH010005.MP4',
    timestamp: 17,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '83',
    frame_image: driving_camera_gh010005_frame_034,
    confidence: 73,
    video_source: 'GH010005.MP4',
    timestamp: 34,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '84',
    frame_image: driving_camera_gh010005_frame_051,
    confidence: 72,
    video_source: 'GH010005.MP4',
    timestamp: 51,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '85',
    frame_image: driving_camera_gh010005_frame_068,
    confidence: 71,
    video_source: 'GH010005.MP4',
    timestamp: 68,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '86',
    frame_image: driving_camera_gh010005_frame_084,
    confidence: 70,
    video_source: 'GH010005.MP4',
    timestamp: 84,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '87',
    frame_image: driving_camera_gh010005_frame_101,
    confidence: 69,
    video_source: 'GH010005.MP4',
    timestamp: 101,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '88',
    frame_image: driving_camera_gh010005_frame_118,
    confidence: 68,
    video_source: 'GH010005.MP4',
    timestamp: 118,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '89',
    frame_image: driving_camera_gh010005_frame_135,
    confidence: 67,
    video_source: 'GH010005.MP4',
    timestamp: 135,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '90',
    frame_image: driving_camera_gh010005_frame_151,
    confidence: 66,
    video_source: 'GH010005.MP4',
    timestamp: 151,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '91',
    frame_image: driving_camera_gh010005_frame_168,
    confidence: 95,
    video_source: 'GH010005.MP4',
    timestamp: 168,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '92',
    frame_image: driving_camera_gh010005_frame_185,
    confidence: 94,
    video_source: 'GH010005.MP4',
    timestamp: 185,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '93',
    frame_image: driving_camera_gh010005_frame_202,
    confidence: 93,
    video_source: 'GH010005.MP4',
    timestamp: 202,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '94',
    frame_image: driving_camera_gh010005_frame_218,
    confidence: 92,
    video_source: 'GH010005.MP4',
    timestamp: 218,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '95',
    frame_image: driving_camera_gh010005_frame_235,
    confidence: 91,
    video_source: 'GH010005.MP4',
    timestamp: 235,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '96',
    frame_image: driving_camera_gh010005_frame_252,
    confidence: 90,
    video_source: 'GH010005.MP4',
    timestamp: 252,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '97',
    frame_image: driving_camera_gh010005_frame_269,
    confidence: 89,
    video_source: 'GH010005.MP4',
    timestamp: 269,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '98',
    frame_image: driving_camera_gh010005_frame_285,
    confidence: 88,
    video_source: 'GH010005.MP4',
    timestamp: 285,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '99',
    frame_image: driving_camera_gh010005_frame_302,
    confidence: 87,
    video_source: 'GH010005.MP4',
    timestamp: 302,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '100',
    frame_image: driving_camera_gh010005_frame_319,
    confidence: 86,
    video_source: 'GH010005.MP4',
    timestamp: 319,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '101',
    frame_image: driving_camera_gh010006_frame_001,
    confidence: 85,
    video_source: 'GH010006.MP4',
    timestamp: 1,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '102',
    frame_image: driving_camera_gh010006_frame_025,
    confidence: 84,
    video_source: 'GH010006.MP4',
    timestamp: 25,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '103',
    frame_image: driving_camera_gh010006_frame_050,
    confidence: 83,
    video_source: 'GH010006.MP4',
    timestamp: 50,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '104',
    frame_image: driving_camera_gh010006_frame_075,
    confidence: 82,
    video_source: 'GH010006.MP4',
    timestamp: 75,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '105',
    frame_image: driving_camera_gh010006_frame_100,
    confidence: 81,
    video_source: 'GH010006.MP4',
    timestamp: 100,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '106',
    frame_image: driving_camera_gh010006_frame_124,
    confidence: 80,
    video_source: 'GH010006.MP4',
    timestamp: 124,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '107',
    frame_image: driving_camera_gh010006_frame_149,
    confidence: 79,
    video_source: 'GH010006.MP4',
    timestamp: 149,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '108',
    frame_image: driving_camera_gh010006_frame_174,
    confidence: 78,
    video_source: 'GH010006.MP4',
    timestamp: 174,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '109',
    frame_image: driving_camera_gh010006_frame_199,
    confidence: 77,
    video_source: 'GH010006.MP4',
    timestamp: 199,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '110',
    frame_image: driving_camera_gh010006_frame_223,
    confidence: 76,
    video_source: 'GH010006.MP4',
    timestamp: 223,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '111',
    frame_image: driving_camera_gh010006_frame_248,
    confidence: 75,
    video_source: 'GH010006.MP4',
    timestamp: 248,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '112',
    frame_image: driving_camera_gh010006_frame_273,
    confidence: 74,
    video_source: 'GH010006.MP4',
    timestamp: 273,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '113',
    frame_image: driving_camera_gh010006_frame_298,
    confidence: 73,
    video_source: 'GH010006.MP4',
    timestamp: 298,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '114',
    frame_image: driving_camera_gh010006_frame_322,
    confidence: 72,
    video_source: 'GH010006.MP4',
    timestamp: 322,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '115',
    frame_image: driving_camera_gh010006_frame_347,
    confidence: 71,
    video_source: 'GH010006.MP4',
    timestamp: 347,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '116',
    frame_image: driving_camera_gh010006_frame_372,
    confidence: 70,
    video_source: 'GH010006.MP4',
    timestamp: 372,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '117',
    frame_image: driving_camera_gh010006_frame_397,
    confidence: 69,
    video_source: 'GH010006.MP4',
    timestamp: 397,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '118',
    frame_image: driving_camera_gh010006_frame_421,
    confidence: 68,
    video_source: 'GH010006.MP4',
    timestamp: 421,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '119',
    frame_image: driving_camera_gh010006_frame_446,
    confidence: 67,
    video_source: 'GH010006.MP4',
    timestamp: 446,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '120',
    frame_image: driving_camera_gh010006_frame_471,
    confidence: 66,
    video_source: 'GH010006.MP4',
    timestamp: 471,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '121',
    frame_image: driving_camera_gh010007_frame_001,
    confidence: 95,
    video_source: 'GH010007.MP4',
    timestamp: 1,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '122',
    frame_image: driving_camera_gh010007_frame_020,
    confidence: 94,
    video_source: 'GH010007.MP4',
    timestamp: 20,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '123',
    frame_image: driving_camera_gh010007_frame_039,
    confidence: 93,
    video_source: 'GH010007.MP4',
    timestamp: 39,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '124',
    frame_image: driving_camera_gh010007_frame_058,
    confidence: 92,
    video_source: 'GH010007.MP4',
    timestamp: 58,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '125',
    frame_image: driving_camera_gh010007_frame_077,
    confidence: 91,
    video_source: 'GH010007.MP4',
    timestamp: 77,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '126',
    frame_image: driving_camera_gh010007_frame_097,
    confidence: 90,
    video_source: 'GH010007.MP4',
    timestamp: 97,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '127',
    frame_image: driving_camera_gh010007_frame_116,
    confidence: 89,
    video_source: 'GH010007.MP4',
    timestamp: 116,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '128',
    frame_image: driving_camera_gh010007_frame_135,
    confidence: 88,
    video_source: 'GH010007.MP4',
    timestamp: 135,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '129',
    frame_image: driving_camera_gh010007_frame_154,
    confidence: 87,
    video_source: 'GH010007.MP4',
    timestamp: 154,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '130',
    frame_image: driving_camera_gh010007_frame_173,
    confidence: 86,
    video_source: 'GH010007.MP4',
    timestamp: 173,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '131',
    frame_image: driving_camera_gh010007_frame_193,
    confidence: 85,
    video_source: 'GH010007.MP4',
    timestamp: 193,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '132',
    frame_image: driving_camera_gh010007_frame_212,
    confidence: 84,
    video_source: 'GH010007.MP4',
    timestamp: 212,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '133',
    frame_image: driving_camera_gh010007_frame_231,
    confidence: 83,
    video_source: 'GH010007.MP4',
    timestamp: 231,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '134',
    frame_image: driving_camera_gh010007_frame_250,
    confidence: 82,
    video_source: 'GH010007.MP4',
    timestamp: 250,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '135',
    frame_image: driving_camera_gh010007_frame_269,
    confidence: 81,
    video_source: 'GH010007.MP4',
    timestamp: 269,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '136',
    frame_image: driving_camera_gh010007_frame_289,
    confidence: 80,
    video_source: 'GH010007.MP4',
    timestamp: 289,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '137',
    frame_image: driving_camera_gh010007_frame_308,
    confidence: 79,
    video_source: 'GH010007.MP4',
    timestamp: 308,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '138',
    frame_image: driving_camera_gh010007_frame_327,
    confidence: 78,
    video_source: 'GH010007.MP4',
    timestamp: 327,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '139',
    frame_image: driving_camera_gh010007_frame_346,
    confidence: 77,
    video_source: 'GH010007.MP4',
    timestamp: 346,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '140',
    frame_image: driving_camera_gh010007_frame_365,
    confidence: 76,
    video_source: 'GH010007.MP4',
    timestamp: 365,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '141',
    frame_image: driving_camera_gh010010_frame_001,
    confidence: 75,
    video_source: 'GH010010.MP4',
    timestamp: 1,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '142',
    frame_image: driving_camera_gh010010_frame_036,
    confidence: 74,
    video_source: 'GH010010.MP4',
    timestamp: 36,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '143',
    frame_image: driving_camera_gh010010_frame_071,
    confidence: 73,
    video_source: 'GH010010.MP4',
    timestamp: 71,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '144',
    frame_image: driving_camera_gh010010_frame_107,
    confidence: 72,
    video_source: 'GH010010.MP4',
    timestamp: 107,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '145',
    frame_image: driving_camera_gh010010_frame_142,
    confidence: 71,
    video_source: 'GH010010.MP4',
    timestamp: 142,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '146',
    frame_image: driving_camera_gh010010_frame_178,
    confidence: 70,
    video_source: 'GH010010.MP4',
    timestamp: 178,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '147',
    frame_image: driving_camera_gh010010_frame_213,
    confidence: 69,
    video_source: 'GH010010.MP4',
    timestamp: 213,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '148',
    frame_image: driving_camera_gh010010_frame_248,
    confidence: 68,
    video_source: 'GH010010.MP4',
    timestamp: 248,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '149',
    frame_image: driving_camera_gh010010_frame_284,
    confidence: 67,
    video_source: 'GH010010.MP4',
    timestamp: 284,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '150',
    frame_image: driving_camera_gh010010_frame_319,
    confidence: 66,
    video_source: 'GH010010.MP4',
    timestamp: 319,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '151',
    frame_image: driving_camera_gh010010_frame_355,
    confidence: 95,
    video_source: 'GH010010.MP4',
    timestamp: 355,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '152',
    frame_image: driving_camera_gh010010_frame_390,
    confidence: 94,
    video_source: 'GH010010.MP4',
    timestamp: 390,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '153',
    frame_image: driving_camera_gh010010_frame_425,
    confidence: 93,
    video_source: 'GH010010.MP4',
    timestamp: 425,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '154',
    frame_image: driving_camera_gh010010_frame_461,
    confidence: 92,
    video_source: 'GH010010.MP4',
    timestamp: 461,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '155',
    frame_image: driving_camera_gh010010_frame_496,
    confidence: 91,
    video_source: 'GH010010.MP4',
    timestamp: 496,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '156',
    frame_image: driving_camera_gh010010_frame_532,
    confidence: 90,
    video_source: 'GH010010.MP4',
    timestamp: 532,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '157',
    frame_image: driving_camera_gh010010_frame_567,
    confidence: 89,
    video_source: 'GH010010.MP4',
    timestamp: 567,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '158',
    frame_image: driving_camera_gh010010_frame_602,
    confidence: 88,
    video_source: 'GH010010.MP4',
    timestamp: 602,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '159',
    frame_image: driving_camera_gh010010_frame_638,
    confidence: 87,
    video_source: 'GH010010.MP4',
    timestamp: 638,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '160',
    frame_image: driving_camera_gh010010_frame_673,
    confidence: 86,
    video_source: 'GH010010.MP4',
    timestamp: 673,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '161',
    frame_image: driving_camera_gh020010_frame_001,
    confidence: 85,
    video_source: 'GH020010.MP4',
    timestamp: 1,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '162',
    frame_image: driving_camera_gh020010_frame_015,
    confidence: 84,
    video_source: 'GH020010.MP4',
    timestamp: 15,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '163',
    frame_image: driving_camera_gh020010_frame_029,
    confidence: 83,
    video_source: 'GH020010.MP4',
    timestamp: 29,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '164',
    frame_image: driving_camera_gh020010_frame_043,
    confidence: 82,
    video_source: 'GH020010.MP4',
    timestamp: 43,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '165',
    frame_image: driving_camera_gh020010_frame_057,
    confidence: 81,
    video_source: 'GH020010.MP4',
    timestamp: 57,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '166',
    frame_image: driving_camera_gh020010_frame_072,
    confidence: 80,
    video_source: 'GH020010.MP4',
    timestamp: 72,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '167',
    frame_image: driving_camera_gh020010_frame_086,
    confidence: 79,
    video_source: 'GH020010.MP4',
    timestamp: 86,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '168',
    frame_image: driving_camera_gh020010_frame_100,
    confidence: 78,
    video_source: 'GH020010.MP4',
    timestamp: 100,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '169',
    frame_image: driving_camera_gh020010_frame_114,
    confidence: 77,
    video_source: 'GH020010.MP4',
    timestamp: 114,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '170',
    frame_image: driving_camera_gh020010_frame_128,
    confidence: 76,
    video_source: 'GH020010.MP4',
    timestamp: 128,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '171',
    frame_image: driving_camera_gh020010_frame_143,
    confidence: 75,
    video_source: 'GH020010.MP4',
    timestamp: 143,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '172',
    frame_image: driving_camera_gh020010_frame_157,
    confidence: 74,
    video_source: 'GH020010.MP4',
    timestamp: 157,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '173',
    frame_image: driving_camera_gh020010_frame_171,
    confidence: 73,
    video_source: 'GH020010.MP4',
    timestamp: 171,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '174',
    frame_image: driving_camera_gh020010_frame_185,
    confidence: 72,
    video_source: 'GH020010.MP4',
    timestamp: 185,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '175',
    frame_image: driving_camera_gh020010_frame_199,
    confidence: 71,
    video_source: 'GH020010.MP4',
    timestamp: 199,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '176',
    frame_image: driving_camera_gh020010_frame_214,
    confidence: 70,
    video_source: 'GH020010.MP4',
    timestamp: 214,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '177',
    frame_image: driving_camera_gh020010_frame_228,
    confidence: 69,
    video_source: 'GH020010.MP4',
    timestamp: 228,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '178',
    frame_image: driving_camera_gh020010_frame_242,
    confidence: 68,
    video_source: 'GH020010.MP4',
    timestamp: 242,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '179',
    frame_image: driving_camera_gh020010_frame_256,
    confidence: 67,
    video_source: 'GH020010.MP4',
    timestamp: 256,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
  {
    id: '180',
    frame_image: driving_camera_gh020010_frame_270,
    confidence: 66,
    video_source: 'GH020010.MP4',
    timestamp: 270,
    metadata: {
      weather: 'sunny',
      time_of_day: 'day',
      location: 'Highway driving',
      category: 'driving_camera'
    }
  },
]
